Make the gtk+ portions of the project optional.
This commit first separates gpicker from gpicker-simple, making them
fully separate binaries, built with different flags. This makes it
easy to then make the building of gpicker optional.

On systems on which gtk+ or gthread is unavailable, or if configure is
passed the argument --without-gtk, only gpicker-simple is available.
gpicker isn't built at all.

diff --git a/configure.ac.in b/configure.ac.in
--- a/configure.ac.in
+++ b/configure.ac.in
@@ -3,10 +3,13 @@ AC_CONFIG_HEADERS(config.h)
 AM_INIT_AUTOMAKE
 AC_CONFIG_FILES([Makefile lib/Makefile])
 AC_PROG_CC
+AM_PROG_CC_C_O
+AC_PROG_RANLIB
 gl_EARLY
 
 AC_ARG_ENABLE(timing, [AS_HELP_STRING(--enable-timing, Enable output of timing info on stderr)],
                       [AC_DEFINE([WITH_TIMING], 1, [Output timing info])])
+AC_ARG_WITH([gtk], AS_HELP_STRING([--without-gtk], [Ignore presence of GTK+ libs]))
 
 # check for 'check' unit-testing framework
 PKG_CHECK_MODULES([check], [check], [HAVE_CHECK=yes], [
@@ -19,14 +22,18 @@ AC_DEFINE([FIND_INVOCATION], ["find . '!' -wholename '*.git/*' -a '!' -wholename
 [ -a '!' -wholename '*.svn/*' -a '!' -wholename '*.bzr/*']dnl
 [ -a '!' -wholename '*CVS/*' -type f -follow -print0"], [Command line to fetch list of files])
 
-PKG_CHECK_MODULES([gtk2], [gtk+-2.0 >= 2.8])
-PKG_CHECK_MODULES([glib2], [glib-2.0 >= 2.14])
-PKG_CHECK_MODULES([gthread], [gthread-2.0])
-
-AC_DEFINE([WITH_GUI], 1, [GUI build])
+HAVE_GTK=no
+AS_IF([test "x$with_gtk" != "xno"], [
+   HAVE_GTK=yes
+   PKG_CHECK_MODULES([gtk2], [gtk+-2.0],, [HAVE_GTK=no])
+   PKG_CHECK_MODULES([gthread], [gthread-2.0],, [HAVE_GTK=no])
+])
+PKG_CHECK_MODULES([glib2], [glib-2.0 >= 2.14],, [echo "glib-2.0 >= 2.14 required." >&2; exit ])
+AM_CONDITIONAL([HAVE_GTK], [test x$HAVE_GTK = xyes])
 
 AC_SUBST(EXTRA_CPPFLAGS)
 
+if test "x$HAVE_GTK" = "xyes"; then
 uname_res=`uname -s`
 if test "x$uname_res" = "xDarwin"; then
   EXTRA_CPPFLAGS=-xobjective-c
@@ -47,6 +54,7 @@ AC_LINK_IFELSE([], [AC_MSG_RESULT([no])], [
 ])
 LIBS=$ac_func_search_save_LIBS
 CFLAGS=$ac_func_search_save_CFLAGS
+fi # HAVE_GTK=1
 
 ac_func_search_save_LIBS=$LIBS
 ac_func_search_save_CFLAGS=$CFLAGS
